# Generated by Django 4.1.7 on 2023-02-15 23:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('altitude', models.FloatField(default=0)),
                ('ebikes', models.IntegerField(default=0)),
                ('has_ebikes', models.BooleanField()),
                ('last_updated', models.IntegerField()),
                ('normal_bikes', models.IntegerField(default=0)),
                ('payment_terminal', models.BooleanField()),
                ('post_code', models.PositiveIntegerField()),
                ('renting', models.IntegerField(default=0)),
                ('returning', models.IntegerField(default=0)),
                ('slots', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('latitude', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('longitude', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=200)),
                ('gbfs_href', models.CharField(max_length=200)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.location')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('empty_slots', models.IntegerField(default=0)),
                ('free_bikes', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('longitude', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('timestamp', models.DateTimeField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.network')),
            ],
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
        migrations.AddField(
            model_name='extra',
            name='station',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.station'),
        ),
    ]
