# Generated by Django 4.1.7 on 2023-02-16 13:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_extra_station_alter_network_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='payment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='company',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[''], size=None),
            preserve_default=False,
        ),
    ]
