# Generated by Django 4.1.7 on 2023-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_extra_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='post_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
